apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-container
          image: 059127482501.dkr.ecr.eu-central-1.amazonaws.com/test-image-repository:flaskapp
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: database-secrets
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend-deployment
  ports:
    - port: 5000
      targetPort: 5000
