apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 256Mi
  storageClassName: local-storage
  hostPath:
    path: /tmp/db
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce