apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cfg
  namespace: default
data:
  FLASK_PORT: "5000"
  FLASK_DEBUG: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-cfg
  namespace: default
data:
  nginx-default.conf.template: |
    server {
        listen 80;

        location /api/ {
            proxy_pass http://${backend_host}:${backend_port}/;
            proxy_redirect default;
        }

        location / {
            proxy_pass http://${frontend_host}:${frontend_port};
        }
    }
