apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: webserver-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
